complete

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,117 +1,98 @@
-name: build
+name: CI/CD Pipeline
 
 on:
   push:
     branches:
-      - "*"
+      - master
   pull_request:
     branches:
-      - "*"  
+      - master
 
 jobs:
-  build:
-    name: ci-pipeline
+  lint:
     runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:11
-        ports:
-          - 5432:5432
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
     steps:
-     - uses: actions/checkout@v2
-     - uses: ruby/setup-ruby@v1
-       with:
-          ruby-version: "3.1.3"
-          bundler-cache: true
-     - name: Install postgres
-       run: sudo apt-get install libpq-dev
-     - name: install dependencies
-       run: |
-              bundle install
-     - name: Setup Database
-       run: |
-          cp config/database.yml.github-actions config/database.yml
-          bundle exec rails db:create
-          bundle exec rails db:schema:load
-       env:
-          RAILS_ENV: test
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-     - name: run-frontend-backend-tests
-       run: |
-          bundle exec rails test
-       env:
-          RAILS_ENV: test
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
+      - name: Check out code
+        uses: actions/checkout@v2
 
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '3.1.3'
+          bundler-cache: true
+
+      - name: Run linting
+        run: |
+          bundle exec rubocop
+
+  build:
+    runs-on: ubuntu-latest
+    needs: lint
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '3.1.3'
+          bundler-cache: true
+
+      - name: Install dependencies
+        run: |
+          bundle install
 
   rubocop:
-    name: Run RuboCop
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - uses: actions/checkout@v2
-      - uses: ruby/setup-ruby@v1
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
         with:
-          ruby-version: "3.1.3"
+          ruby-version: '3.1.3'
           bundler-cache: true
-      - name: Install dependencies
-        run: bundle install
+
       - name: Run RuboCop
-        run: bundle exec rubocop
+        run: |
+          rubocop --format json --out rubocop_output.json || true
+          if [[ $(jq '.summary.offense_count' rubocop_output.json) -gt 0 ]]; then
+            echo "RuboCop offenses detected. Failing the job."
+            exit 1
+          fi
 
   rspec:
-    name: Run RSpec
     runs-on: ubuntu-latest
-    needs: build
+    needs: rubocop
     steps:
-      - uses: actions/checkout@v2
-      - uses: ruby/setup-ruby@v1
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
         with:
-          ruby-version: "3.1.3"
+          ruby-version: '3.1.3'
           bundler-cache: true
-      - name: Install dependencies
-        run: bundle install
+
       - name: Run RSpec
-        run: bundle exec rspec
+        run: |
+          bundle exec rspec --format documentation
 
   cucumber:
-    name: Run Cucumber
     runs-on: ubuntu-latest
-    needs: build
+    needs: rspec
     steps:
-      - uses: actions/checkout@v2
-      - uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: "3.1.3"
-          bundler-cache: true
-      - name: Install dependencies
-        run: bundle install
-      - name: Run Cucumber
-        run: bundle exec cucumber
-
-  deployProduction:
-    name: cd-pipeline-production
-    needs: [build]
-    if: github.ref == 'refs/heads/master'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out repository
+      - name: Check out code
         uses: actions/checkout@v2
-      - name: Login into Heroku
-        uses: akhileshns/heroku-deploy@v3.12.12
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
         with:
-          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
-          heroku_app_name: shockwave-kickers
-          heroku_email: kvudathu@tamu.edu
-      - name: Add Heroku remote
-        run: heroku git:remote --app shockwave-kickers
-        env:
-          HEROKU_APP_NAME: shockwave-kickers
-      - name: Migrate DB if needed
-        run: heroku run rails db:migrate
+          ruby-version: '3.1.3'
+          bundler-cache: true
+
+      - name: Run Cucumber
+        run: |
+          bundle exec cucumber
